name: "gau "
description: "getallurls (gau) fetches known URLs from many public resource."
branding:
  icon: "activity"
  color: "blue"

inputs:
  urls:
    description: "List of urls to scan"
    required: false

  output:
    description: "File to save output result"
    required: false
    default: "gau.log"    

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/gau ] && go install -v github.com/lc/gau/v2/cmd/gau@latest
        [ ! -z ${{ inputs.urls }} ] && echo "urls=${{ inputs.urls}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.output }} ] && echo "output=--o ${{ inputs.output}}" >> $GITHUB_ENV      
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        echo ${{ env.urls }}
        echo ${{ env.urls }} | gau  --threads 10 
      shell: bash
